# Site settings
title: William
header-img: img/home-bg.jpg
email: 406853323@qq.com
description: "Blog of William. Read about my projects."
baseurl: ""
url: "https://dawoshi.github.io"
facebook_username: William
github_username: dawoshi
linkedin_username:

# Build settings
markdown: kramdown
highlighter: rouge
future: true
permalink: /:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

analytics :
  provider : google
  google : 
    tracking_id : 'UA-89904117-1'
  getclicky :
    site_id : 
